package com.brm.etl;

import org.apache.commons.lang3.builder.ReflectionToStringBuilder;
import org.apache.commons.lang3.builder.ToStringStyle;

public class Comtsmsdh {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column KUHDBA.COMTSMSDH.SENDID
     *
     * @mbg.generated Mon Mar 13 13:38:42 KST 2017
     */
    private String SENDID;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column KUHDBA.COMTSMSDH.INDATE
     *
     * @mbg.generated Mon Mar 13 13:38:42 KST 2017
     */
    private String INDATE;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column KUHDBA.COMTSMSDH.INTIME
     *
     * @mbg.generated Mon Mar 13 13:38:42 KST 2017
     */
    private String INTIME;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column KUHDBA.COMTSMSDH.C_SEQNO
     *
     * @mbg.generated Mon Mar 13 13:38:42 KST 2017
     */
    private Integer c_SEQNO;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column KUHDBA.COMTSMSDH.MEMBER
     *
     * @mbg.generated Mon Mar 13 13:38:42 KST 2017
     */
    private Long MEMBER;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column KUHDBA.COMTSMSDH.SPHONE1
     *
     * @mbg.generated Mon Mar 13 13:38:42 KST 2017
     */
    private String SPHONE1;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column KUHDBA.COMTSMSDH.SPHONE2
     *
     * @mbg.generated Mon Mar 13 13:38:42 KST 2017
     */
    private String SPHONE2;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column KUHDBA.COMTSMSDH.SPHONE3
     *
     * @mbg.generated Mon Mar 13 13:38:42 KST 2017
     */
    private String SPHONE3;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column KUHDBA.COMTSMSDH.SENDNAME
     *
     * @mbg.generated Mon Mar 13 13:38:42 KST 2017
     */
    private String SENDNAME;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column KUHDBA.COMTSMSDH.RPHONE1
     *
     * @mbg.generated Mon Mar 13 13:38:42 KST 2017
     */
    private String RPHONE1;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column KUHDBA.COMTSMSDH.RPHONE2
     *
     * @mbg.generated Mon Mar 13 13:38:42 KST 2017
     */
    private String RPHONE2;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column KUHDBA.COMTSMSDH.RPHONE3
     *
     * @mbg.generated Mon Mar 13 13:38:42 KST 2017
     */
    private String RPHONE3;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column KUHDBA.COMTSMSDH.RECVNAME
     *
     * @mbg.generated Mon Mar 13 13:38:42 KST 2017
     */
    private String RECVNAME;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column KUHDBA.COMTSMSDH.MSG
     *
     * @mbg.generated Mon Mar 13 13:38:42 KST 2017
     */
    private String MSG;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column KUHDBA.COMTSMSDH.URL
     *
     * @mbg.generated Mon Mar 13 13:38:42 KST 2017
     */
    private String URL;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column KUHDBA.COMTSMSDH.RDATE
     *
     * @mbg.generated Mon Mar 13 13:38:42 KST 2017
     */
    private String RDATE;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column KUHDBA.COMTSMSDH.RTIME
     *
     * @mbg.generated Mon Mar 13 13:38:42 KST 2017
     */
    private String RTIME;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column KUHDBA.COMTSMSDH.RESULT
     *
     * @mbg.generated Mon Mar 13 13:38:42 KST 2017
     */
    private String RESULT;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column KUHDBA.COMTSMSDH.KIND
     *
     * @mbg.generated Mon Mar 13 13:38:42 KST 2017
     */
    private String KIND;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column KUHDBA.COMTSMSDH.ERRCODE
     *
     * @mbg.generated Mon Mar 13 13:38:42 KST 2017
     */
    private Short ERRCODE;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column KUHDBA.COMTSMSDH.C_RESULT
     *
     * @mbg.generated Mon Mar 13 13:38:42 KST 2017
     */
    private String c_RESULT;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column KUHDBA.COMTSMSDH.C_PID
     *
     * @mbg.generated Mon Mar 13 13:38:42 KST 2017
     */
    private String c_PID;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column KUHDBA.COMTSMSDH.C_SENDTIME
     *
     * @mbg.generated Mon Mar 13 13:38:42 KST 2017
     */
    private String c_SENDTIME;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column KUHDBA.COMTSMSDH.C_MSGID
     *
     * @mbg.generated Mon Mar 13 13:38:42 KST 2017
     */
    private String c_MSGID;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column KUHDBA.COMTSMSDH.C_MSGPARAM
     *
     * @mbg.generated Mon Mar 13 13:38:42 KST 2017
     */
    private String c_MSGPARAM;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column KUHDBA.COMTSMSDH.SEQNO
     *
     * @mbg.generated Mon Mar 13 13:38:42 KST 2017
     */
    private Long SEQNO;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column KUHDBA.COMTSMSDH.C_USERID
     *
     * @mbg.generated Mon Mar 13 13:38:42 KST 2017
     */
    private String c_USERID;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column KUHDBA.COMTSMSDH.SYSINFO
     *
     * @mbg.generated Mon Mar 13 13:38:42 KST 2017
     */
    private String SYSINFO;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column KUHDBA.COMTSMSDH.RECVTIME
     *
     * @mbg.generated Mon Mar 13 13:38:42 KST 2017
     */
    private String RECVTIME;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column KUHDBA.COMTSMSDH.MEDIATYPE
     *
     * @mbg.generated Mon Mar 13 13:38:42 KST 2017
     */
    private String MEDIATYPE;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column KUHDBA.COMTSMSDH.TEMPLET
     *
     * @mbg.generated Mon Mar 13 13:38:42 KST 2017
     */
    private String TEMPLET;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column KUHDBA.COMTSMSDH.SENDID
     *
     * @return the value of KUHDBA.COMTSMSDH.SENDID
     *
     * @mbg.generated Mon Mar 13 13:38:42 KST 2017
     */
    public String getSENDID() {
        return SENDID;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column KUHDBA.COMTSMSDH.SENDID
     *
     * @param SENDID the value for KUHDBA.COMTSMSDH.SENDID
     *
     * @mbg.generated Mon Mar 13 13:38:42 KST 2017
     */
    public void setSENDID(String SENDID) {
        this.SENDID = SENDID;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column KUHDBA.COMTSMSDH.INDATE
     *
     * @return the value of KUHDBA.COMTSMSDH.INDATE
     *
     * @mbg.generated Mon Mar 13 13:38:42 KST 2017
     */
    public String getINDATE() {
        return INDATE;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column KUHDBA.COMTSMSDH.INDATE
     *
     * @param INDATE the value for KUHDBA.COMTSMSDH.INDATE
     *
     * @mbg.generated Mon Mar 13 13:38:42 KST 2017
     */
    public void setINDATE(String INDATE) {
        this.INDATE = INDATE;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column KUHDBA.COMTSMSDH.INTIME
     *
     * @return the value of KUHDBA.COMTSMSDH.INTIME
     *
     * @mbg.generated Mon Mar 13 13:38:42 KST 2017
     */
    public String getINTIME() {
        return INTIME;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column KUHDBA.COMTSMSDH.INTIME
     *
     * @param INTIME the value for KUHDBA.COMTSMSDH.INTIME
     *
     * @mbg.generated Mon Mar 13 13:38:42 KST 2017
     */
    public void setINTIME(String INTIME) {
        this.INTIME = INTIME;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column KUHDBA.COMTSMSDH.C_SEQNO
     *
     * @return the value of KUHDBA.COMTSMSDH.C_SEQNO
     *
     * @mbg.generated Mon Mar 13 13:38:42 KST 2017
     */
    public Integer getC_SEQNO() {
        return c_SEQNO;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column KUHDBA.COMTSMSDH.C_SEQNO
     *
     * @param c_SEQNO the value for KUHDBA.COMTSMSDH.C_SEQNO
     *
     * @mbg.generated Mon Mar 13 13:38:42 KST 2017
     */
    public void setC_SEQNO(Integer c_SEQNO) {
        this.c_SEQNO = c_SEQNO;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column KUHDBA.COMTSMSDH.MEMBER
     *
     * @return the value of KUHDBA.COMTSMSDH.MEMBER
     *
     * @mbg.generated Mon Mar 13 13:38:42 KST 2017
     */
    public Long getMEMBER() {
        return MEMBER;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column KUHDBA.COMTSMSDH.MEMBER
     *
     * @param MEMBER the value for KUHDBA.COMTSMSDH.MEMBER
     *
     * @mbg.generated Mon Mar 13 13:38:42 KST 2017
     */
    public void setMEMBER(Long MEMBER) {
        this.MEMBER = MEMBER;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column KUHDBA.COMTSMSDH.SPHONE1
     *
     * @return the value of KUHDBA.COMTSMSDH.SPHONE1
     *
     * @mbg.generated Mon Mar 13 13:38:42 KST 2017
     */
    public String getSPHONE1() {
        return SPHONE1;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column KUHDBA.COMTSMSDH.SPHONE1
     *
     * @param SPHONE1 the value for KUHDBA.COMTSMSDH.SPHONE1
     *
     * @mbg.generated Mon Mar 13 13:38:42 KST 2017
     */
    public void setSPHONE1(String SPHONE1) {
        this.SPHONE1 = SPHONE1;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column KUHDBA.COMTSMSDH.SPHONE2
     *
     * @return the value of KUHDBA.COMTSMSDH.SPHONE2
     *
     * @mbg.generated Mon Mar 13 13:38:42 KST 2017
     */
    public String getSPHONE2() {
        return SPHONE2;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column KUHDBA.COMTSMSDH.SPHONE2
     *
     * @param SPHONE2 the value for KUHDBA.COMTSMSDH.SPHONE2
     *
     * @mbg.generated Mon Mar 13 13:38:42 KST 2017
     */
    public void setSPHONE2(String SPHONE2) {
        this.SPHONE2 = SPHONE2;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column KUHDBA.COMTSMSDH.SPHONE3
     *
     * @return the value of KUHDBA.COMTSMSDH.SPHONE3
     *
     * @mbg.generated Mon Mar 13 13:38:42 KST 2017
     */
    public String getSPHONE3() {
        return SPHONE3;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column KUHDBA.COMTSMSDH.SPHONE3
     *
     * @param SPHONE3 the value for KUHDBA.COMTSMSDH.SPHONE3
     *
     * @mbg.generated Mon Mar 13 13:38:42 KST 2017
     */
    public void setSPHONE3(String SPHONE3) {
        this.SPHONE3 = SPHONE3;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column KUHDBA.COMTSMSDH.SENDNAME
     *
     * @return the value of KUHDBA.COMTSMSDH.SENDNAME
     *
     * @mbg.generated Mon Mar 13 13:38:42 KST 2017
     */
    public String getSENDNAME() {
        return SENDNAME;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column KUHDBA.COMTSMSDH.SENDNAME
     *
     * @param SENDNAME the value for KUHDBA.COMTSMSDH.SENDNAME
     *
     * @mbg.generated Mon Mar 13 13:38:42 KST 2017
     */
    public void setSENDNAME(String SENDNAME) {
        this.SENDNAME = SENDNAME;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column KUHDBA.COMTSMSDH.RPHONE1
     *
     * @return the value of KUHDBA.COMTSMSDH.RPHONE1
     *
     * @mbg.generated Mon Mar 13 13:38:42 KST 2017
     */
    public String getRPHONE1() {
        return RPHONE1;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column KUHDBA.COMTSMSDH.RPHONE1
     *
     * @param RPHONE1 the value for KUHDBA.COMTSMSDH.RPHONE1
     *
     * @mbg.generated Mon Mar 13 13:38:42 KST 2017
     */
    public void setRPHONE1(String RPHONE1) {
        this.RPHONE1 = RPHONE1;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column KUHDBA.COMTSMSDH.RPHONE2
     *
     * @return the value of KUHDBA.COMTSMSDH.RPHONE2
     *
     * @mbg.generated Mon Mar 13 13:38:42 KST 2017
     */
    public String getRPHONE2() {
        return RPHONE2;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column KUHDBA.COMTSMSDH.RPHONE2
     *
     * @param RPHONE2 the value for KUHDBA.COMTSMSDH.RPHONE2
     *
     * @mbg.generated Mon Mar 13 13:38:42 KST 2017
     */
    public void setRPHONE2(String RPHONE2) {
        this.RPHONE2 = RPHONE2;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column KUHDBA.COMTSMSDH.RPHONE3
     *
     * @return the value of KUHDBA.COMTSMSDH.RPHONE3
     *
     * @mbg.generated Mon Mar 13 13:38:42 KST 2017
     */
    public String getRPHONE3() {
        return RPHONE3;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column KUHDBA.COMTSMSDH.RPHONE3
     *
     * @param RPHONE3 the value for KUHDBA.COMTSMSDH.RPHONE3
     *
     * @mbg.generated Mon Mar 13 13:38:42 KST 2017
     */
    public void setRPHONE3(String RPHONE3) {
        this.RPHONE3 = RPHONE3;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column KUHDBA.COMTSMSDH.RECVNAME
     *
     * @return the value of KUHDBA.COMTSMSDH.RECVNAME
     *
     * @mbg.generated Mon Mar 13 13:38:42 KST 2017
     */
    public String getRECVNAME() {
        return RECVNAME;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column KUHDBA.COMTSMSDH.RECVNAME
     *
     * @param RECVNAME the value for KUHDBA.COMTSMSDH.RECVNAME
     *
     * @mbg.generated Mon Mar 13 13:38:42 KST 2017
     */
    public void setRECVNAME(String RECVNAME) {
        this.RECVNAME = RECVNAME;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column KUHDBA.COMTSMSDH.MSG
     *
     * @return the value of KUHDBA.COMTSMSDH.MSG
     *
     * @mbg.generated Mon Mar 13 13:38:42 KST 2017
     */
    public String getMSG() {
        return MSG;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column KUHDBA.COMTSMSDH.MSG
     *
     * @param MSG the value for KUHDBA.COMTSMSDH.MSG
     *
     * @mbg.generated Mon Mar 13 13:38:42 KST 2017
     */
    public void setMSG(String MSG) {
        this.MSG = MSG;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column KUHDBA.COMTSMSDH.URL
     *
     * @return the value of KUHDBA.COMTSMSDH.URL
     *
     * @mbg.generated Mon Mar 13 13:38:42 KST 2017
     */
    public String getURL() {
        return URL;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column KUHDBA.COMTSMSDH.URL
     *
     * @param URL the value for KUHDBA.COMTSMSDH.URL
     *
     * @mbg.generated Mon Mar 13 13:38:42 KST 2017
     */
    public void setURL(String URL) {
        this.URL = URL;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column KUHDBA.COMTSMSDH.RDATE
     *
     * @return the value of KUHDBA.COMTSMSDH.RDATE
     *
     * @mbg.generated Mon Mar 13 13:38:42 KST 2017
     */
    public String getRDATE() {
        return RDATE;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column KUHDBA.COMTSMSDH.RDATE
     *
     * @param RDATE the value for KUHDBA.COMTSMSDH.RDATE
     *
     * @mbg.generated Mon Mar 13 13:38:42 KST 2017
     */
    public void setRDATE(String RDATE) {
        this.RDATE = RDATE;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column KUHDBA.COMTSMSDH.RTIME
     *
     * @return the value of KUHDBA.COMTSMSDH.RTIME
     *
     * @mbg.generated Mon Mar 13 13:38:42 KST 2017
     */
    public String getRTIME() {
        return RTIME;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column KUHDBA.COMTSMSDH.RTIME
     *
     * @param RTIME the value for KUHDBA.COMTSMSDH.RTIME
     *
     * @mbg.generated Mon Mar 13 13:38:42 KST 2017
     */
    public void setRTIME(String RTIME) {
        this.RTIME = RTIME;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column KUHDBA.COMTSMSDH.RESULT
     *
     * @return the value of KUHDBA.COMTSMSDH.RESULT
     *
     * @mbg.generated Mon Mar 13 13:38:42 KST 2017
     */
    public String getRESULT() {
        return RESULT;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column KUHDBA.COMTSMSDH.RESULT
     *
     * @param RESULT the value for KUHDBA.COMTSMSDH.RESULT
     *
     * @mbg.generated Mon Mar 13 13:38:42 KST 2017
     */
    public void setRESULT(String RESULT) {
        this.RESULT = RESULT;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column KUHDBA.COMTSMSDH.KIND
     *
     * @return the value of KUHDBA.COMTSMSDH.KIND
     *
     * @mbg.generated Mon Mar 13 13:38:42 KST 2017
     */
    public String getKIND() {
        return KIND;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column KUHDBA.COMTSMSDH.KIND
     *
     * @param KIND the value for KUHDBA.COMTSMSDH.KIND
     *
     * @mbg.generated Mon Mar 13 13:38:42 KST 2017
     */
    public void setKIND(String KIND) {
        this.KIND = KIND;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column KUHDBA.COMTSMSDH.ERRCODE
     *
     * @return the value of KUHDBA.COMTSMSDH.ERRCODE
     *
     * @mbg.generated Mon Mar 13 13:38:42 KST 2017
     */
    public Short getERRCODE() {
        return ERRCODE;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column KUHDBA.COMTSMSDH.ERRCODE
     *
     * @param ERRCODE the value for KUHDBA.COMTSMSDH.ERRCODE
     *
     * @mbg.generated Mon Mar 13 13:38:42 KST 2017
     */
    public void setERRCODE(Short ERRCODE) {
        this.ERRCODE = ERRCODE;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column KUHDBA.COMTSMSDH.C_RESULT
     *
     * @return the value of KUHDBA.COMTSMSDH.C_RESULT
     *
     * @mbg.generated Mon Mar 13 13:38:42 KST 2017
     */
    public String getC_RESULT() {
        return c_RESULT;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column KUHDBA.COMTSMSDH.C_RESULT
     *
     * @param c_RESULT the value for KUHDBA.COMTSMSDH.C_RESULT
     *
     * @mbg.generated Mon Mar 13 13:38:42 KST 2017
     */
    public void setC_RESULT(String c_RESULT) {
        this.c_RESULT = c_RESULT;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column KUHDBA.COMTSMSDH.C_PID
     *
     * @return the value of KUHDBA.COMTSMSDH.C_PID
     *
     * @mbg.generated Mon Mar 13 13:38:42 KST 2017
     */
    public String getC_PID() {
        return c_PID;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column KUHDBA.COMTSMSDH.C_PID
     *
     * @param c_PID the value for KUHDBA.COMTSMSDH.C_PID
     *
     * @mbg.generated Mon Mar 13 13:38:42 KST 2017
     */
    public void setC_PID(String c_PID) {
        this.c_PID = c_PID;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column KUHDBA.COMTSMSDH.C_SENDTIME
     *
     * @return the value of KUHDBA.COMTSMSDH.C_SENDTIME
     *
     * @mbg.generated Mon Mar 13 13:38:42 KST 2017
     */
    public String getC_SENDTIME() {
        return c_SENDTIME;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column KUHDBA.COMTSMSDH.C_SENDTIME
     *
     * @param c_SENDTIME the value for KUHDBA.COMTSMSDH.C_SENDTIME
     *
     * @mbg.generated Mon Mar 13 13:38:42 KST 2017
     */
    public void setC_SENDTIME(String c_SENDTIME) {
        this.c_SENDTIME = c_SENDTIME;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column KUHDBA.COMTSMSDH.C_MSGID
     *
     * @return the value of KUHDBA.COMTSMSDH.C_MSGID
     *
     * @mbg.generated Mon Mar 13 13:38:42 KST 2017
     */
    public String getC_MSGID() {
        return c_MSGID;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column KUHDBA.COMTSMSDH.C_MSGID
     *
     * @param c_MSGID the value for KUHDBA.COMTSMSDH.C_MSGID
     *
     * @mbg.generated Mon Mar 13 13:38:42 KST 2017
     */
    public void setC_MSGID(String c_MSGID) {
        this.c_MSGID = c_MSGID;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column KUHDBA.COMTSMSDH.C_MSGPARAM
     *
     * @return the value of KUHDBA.COMTSMSDH.C_MSGPARAM
     *
     * @mbg.generated Mon Mar 13 13:38:42 KST 2017
     */
    public String getC_MSGPARAM() {
        return c_MSGPARAM;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column KUHDBA.COMTSMSDH.C_MSGPARAM
     *
     * @param c_MSGPARAM the value for KUHDBA.COMTSMSDH.C_MSGPARAM
     *
     * @mbg.generated Mon Mar 13 13:38:42 KST 2017
     */
    public void setC_MSGPARAM(String c_MSGPARAM) {
        this.c_MSGPARAM = c_MSGPARAM;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column KUHDBA.COMTSMSDH.SEQNO
     *
     * @return the value of KUHDBA.COMTSMSDH.SEQNO
     *
     * @mbg.generated Mon Mar 13 13:38:42 KST 2017
     */
    public Long getSEQNO() {
        return SEQNO;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column KUHDBA.COMTSMSDH.SEQNO
     *
     * @param SEQNO the value for KUHDBA.COMTSMSDH.SEQNO
     *
     * @mbg.generated Mon Mar 13 13:38:42 KST 2017
     */
    public void setSEQNO(Long SEQNO) {
        this.SEQNO = SEQNO;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column KUHDBA.COMTSMSDH.C_USERID
     *
     * @return the value of KUHDBA.COMTSMSDH.C_USERID
     *
     * @mbg.generated Mon Mar 13 13:38:42 KST 2017
     */
    public String getC_USERID() {
        return c_USERID;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column KUHDBA.COMTSMSDH.C_USERID
     *
     * @param c_USERID the value for KUHDBA.COMTSMSDH.C_USERID
     *
     * @mbg.generated Mon Mar 13 13:38:42 KST 2017
     */
    public void setC_USERID(String c_USERID) {
        this.c_USERID = c_USERID;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column KUHDBA.COMTSMSDH.SYSINFO
     *
     * @return the value of KUHDBA.COMTSMSDH.SYSINFO
     *
     * @mbg.generated Mon Mar 13 13:38:42 KST 2017
     */
    public String getSYSINFO() {
        return SYSINFO;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column KUHDBA.COMTSMSDH.SYSINFO
     *
     * @param SYSINFO the value for KUHDBA.COMTSMSDH.SYSINFO
     *
     * @mbg.generated Mon Mar 13 13:38:42 KST 2017
     */
    public void setSYSINFO(String SYSINFO) {
        this.SYSINFO = SYSINFO;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column KUHDBA.COMTSMSDH.RECVTIME
     *
     * @return the value of KUHDBA.COMTSMSDH.RECVTIME
     *
     * @mbg.generated Mon Mar 13 13:38:42 KST 2017
     */
    public String getRECVTIME() {
        return RECVTIME;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column KUHDBA.COMTSMSDH.RECVTIME
     *
     * @param RECVTIME the value for KUHDBA.COMTSMSDH.RECVTIME
     *
     * @mbg.generated Mon Mar 13 13:38:42 KST 2017
     */
    public void setRECVTIME(String RECVTIME) {
        this.RECVTIME = RECVTIME;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column KUHDBA.COMTSMSDH.MEDIATYPE
     *
     * @return the value of KUHDBA.COMTSMSDH.MEDIATYPE
     *
     * @mbg.generated Mon Mar 13 13:38:42 KST 2017
     */
    public String getMEDIATYPE() {
        return MEDIATYPE;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column KUHDBA.COMTSMSDH.MEDIATYPE
     *
     * @param MEDIATYPE the value for KUHDBA.COMTSMSDH.MEDIATYPE
     *
     * @mbg.generated Mon Mar 13 13:38:42 KST 2017
     */
    public void setMEDIATYPE(String MEDIATYPE) {
        this.MEDIATYPE = MEDIATYPE;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column KUHDBA.COMTSMSDH.TEMPLET
     *
     * @return the value of KUHDBA.COMTSMSDH.TEMPLET
     *
     * @mbg.generated Mon Mar 13 13:38:42 KST 2017
     */
    public String getTEMPLET() {
        return TEMPLET;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column KUHDBA.COMTSMSDH.TEMPLET
     *
     * @param TEMPLET the value for KUHDBA.COMTSMSDH.TEMPLET
     *
     * @mbg.generated Mon Mar 13 13:38:42 KST 2017
     */
    public void setTEMPLET(String TEMPLET) {
        this.TEMPLET = TEMPLET;
    }
    
    @Override
	public String toString() {
		return ReflectionToStringBuilder.toString(this, ToStringStyle.JSON_STYLE);
	}
}