CREATE TABLE BUILDING_INFO (
  DONGCODE                  VARCHAR(30)     DEFAULT NULL,
  SIDO                      VARCHAR(120)    DEFAULT NULL,
  SIGUNGU                   VARCHAR(120)    DEFAULT NULL,
  DONG                      VARCHAR(120)    DEFAULT NULL,
  RI                        VARCHAR(120)    DEFAULT NULL,
  ISMOUNTAIN                CHAR(1)         DEFAULT '0',
  JIBUN1                    NUMBER(4)          NOT NULL,
  JIBUN2                    NUMBER(4)          NOT NULL,
  STREETCODE                CHAR(12)        DEFAULT NULL,
  STREET                    VARCHAR(240)    DEFAULT NULL,
  ISUNDER                   CHAR(1)         DEFAULT NULL,
  BUILDINGNUM1              NUMBER(5)       DEFAULT NULL,
  BUILDINGNUM2              NUMBER(5)       DEFAULT NULL,
  BUILDING                  VARCHAR(120)    DEFAULT NULL,
  BUILDINGDETAIL            VARCHAR(300)    DEFAULT NULL,
  BUILDINGCODE              VARCHAR(25)     DEFAULT '',
  DONGSEQ                   VARCHAR(2)      DEFAULT NULL,
  HAENGDONGCODE             VARCHAR(10)     DEFAULT NULL,
  HAENGDONG                 VARCHAR(60)     DEFAULT NULL,
  ZIPCODE                   VARCHAR(5)      DEFAULT NULL,
  ZIPSEQ                    VARCHAR(3)      DEFAULT NULL,
  MASSDESTINATION           VARCHAR(120)    DEFAULT NULL,
  MOVEREASION               CHAR(2)         DEFAULT NULL,
  GOSIDATE                  CHAR(8)         DEFAULT NULL,
  OLDADDRESS                VARCHAR(75)     DEFAULT NULL,
  SIGUNGUBUILDING           VARCHAR(600)    DEFAULT NULL,
  APT                       CHAR(1)         NOT NULL,
  BASICDESTRICTNUM		      CHAR(5)         DEFAULT NULL,
  ISASIGNDETAILADDR	        CHAR(1)         DEFAULT NULL,
  REMARK1	          	      VARCHAR(45)     DEFAULT NULL,
  REMARK2	 	                VARCHAR(45)     DEFAULT NULL,
  PRIMARY KEY  (BUILDINGCODE)
);

COMMENT ON COLUMN BUILDING_INFO.DONGCODE IS      '법정동코드[10자리]';
COMMENT ON COLUMN BUILDING_INFO.SIDO IS            '시도명';
COMMENT ON COLUMN BUILDING_INFO.SIGUNGU IS        '시군구명';
COMMENT ON COLUMN BUILDING_INFO.DONG IS           '법정읍면동명';
COMMENT ON COLUMN BUILDING_INFO.RI IS             '법정리명';
COMMENT ON COLUMN BUILDING_INFO.ISMOUNTAIN IS     '산여부(0:토지,1:산)(PK2)';
COMMENT ON COLUMN BUILDING_INFO.JIBUN1 IS         '관련지번본번';
COMMENT ON COLUMN BUILDING_INFO.JIBUN2 IS         '관련지번부번';
COMMENT ON COLUMN BUILDING_INFO.STREETCODE IS     '도로명코드';
COMMENT ON COLUMN BUILDING_INFO.STREET IS         '도로명';
COMMENT ON COLUMN BUILDING_INFO.ISUNDER IS        '지하여부(0:지상,1:지하,2:공중)';
COMMENT ON COLUMN BUILDING_INFO.BUILDINGNUM1 IS   '건물본번';
COMMENT ON COLUMN BUILDING_INFO.BUILDINGNUM2 IS   '건물부번';
COMMENT ON COLUMN BUILDING_INFO.BUILDING IS       '건축물대장 건물명';
COMMENT ON COLUMN BUILDING_INFO.BUILDINGDETAIL IS '상세건물명';
COMMENT ON COLUMN BUILDING_INFO.BUILDINGCODE IS   '건물관리번호(PK)';
COMMENT ON COLUMN BUILDING_INFO.DONGSEQ IS        '읍면동일련번호';
COMMENT ON COLUMN BUILDING_INFO.HAENGDONGCODE IS  '행정동코드';
COMMENT ON COLUMN BUILDING_INFO.HAENGDONG IS      '행정동명';
COMMENT ON COLUMN BUILDING_INFO.ZIPCODE IS        '우편번호';
COMMENT ON COLUMN BUILDING_INFO.ZIPSEQ IS         '우편일련번호';
COMMENT ON COLUMN BUILDING_INFO.MASSDESTINATION IS '다량배달처명';
COMMENT ON COLUMN BUILDING_INFO.MOVEREASION      IS '이동사유코드';
COMMENT ON COLUMN BUILDING_INFO.GOSIDATE         IS '고시일자';
COMMENT ON COLUMN BUILDING_INFO.OLDADDRESS       IS '변경전도로명주소';
COMMENT ON COLUMN BUILDING_INFO.SIGUNGUBUILDING  IS '신군구용 건물명';
COMMENT ON COLUMN BUILDING_INFO.APT              IS '공동주택여부';
COMMENT ON COLUMN BUILDING_INFO.BASICDESTRICTNUM         IS '기초구역번호';
COMMENT ON COLUMN BUILDING_INFO.ISASIGNDETAILADDR        IS '상세주소 부여여부';
COMMENT ON COLUMN BUILDING_INFO.REMARK1                  IS '비고1';
COMMENT ON COLUMN BUILDING_INFO.REMARK2                  IS '비고2';


CREATE INDEX IDX_STREET ON BUILDING_INFO ( STREET );
CREATE INDEX IDX_DONG ON BUILDING_INFO ( DONG );
CREATE INDEX IDX_BUILDING ON BUILDING_INFO ( BUILDING );
CREATE INDEX IDX_MASSDESTINATION ON BUILDING_INFO ( MASSDESTINATION );
CREATE INDEX IDX_ZIPCODE ON BUILDING_INFO ( ZIPCODE );


