  CREATE TABLE COMTSMSDH
   (
    SENDID VARCHAR2(16 BYTE) NOT NULL ENABLE,
	INDATE VARCHAR2(8 BYTE) NOT NULL ENABLE,
	INTIME VARCHAR2(6 BYTE) NOT NULL ENABLE,
	C_SEQNO NUMBER(9,0) NOT NULL ENABLE,
	MEMBER NUMBER(10,0) DEFAULT 0 NOT NULL ENABLE,
	SPHONE1 VARCHAR2(4 BYTE),
	SPHONE2 VARCHAR2(4 BYTE),
	SPHONE3 VARCHAR2(4 BYTE),
	SENDNAME VARCHAR2(32 BYTE) NOT NULL ENABLE,
	RPHONE1 VARCHAR2(4 BYTE) NOT NULL ENABLE,
	RPHONE2 VARCHAR2(4 BYTE) NOT NULL ENABLE,
	RPHONE3 VARCHAR2(4 BYTE) NOT NULL ENABLE,
	RECVNAME VARCHAR2(32 BYTE),
	MSG VARCHAR2(4000 BYTE),
	URL VARCHAR2(80 BYTE),
	RDATE VARCHAR2(8 BYTE),
	RTIME VARCHAR2(8 BYTE),
	RESULT VARCHAR2(1 BYTE) NOT NULL ENABLE,
	KIND VARCHAR2(1 BYTE) DEFAULT 'S' NOT NULL ENABLE,
	ERRCODE NUMBER(4,0),
	C_RESULT VARCHAR2(1 BYTE) DEFAULT 'A' NOT NULL ENABLE,
	C_PID VARCHAR2(11 BYTE),
	C_SENDTIME VARCHAR2(17 BYTE),
	C_MSGID VARCHAR2(11 BYTE),
	C_MSGPARAM VARCHAR2(1000 BYTE),
	SEQNO NUMBER(11,0),
	C_USERID VARCHAR2(8 BYTE),
	SYSINFO VARCHAR2(1 BYTE),
	RECVTIME VARCHAR2(16 BYTE),
	MEDIATYPE VARCHAR2(1 BYTE),
	TEMPLET VARCHAR2(15 BYTE),
	CONSTRAINT PK_COMTSMSDH PRIMARY KEY (SENDID, INDATE, INTIME, C_SEQNO)
	);

   COMMENT ON COLUMN COMTSMSDH.SENDID IS '전송 ID';
   COMMENT ON COLUMN COMTSMSDH.INDATE IS '문자 전송 메시지를 입력한 날짜';
   COMMENT ON COLUMN COMTSMSDH.INTIME IS '문자 전송 메시지를 입력한 시간';
   COMMENT ON COLUMN COMTSMSDH.C_SEQNO IS '문자 전송 메시지 일련번호';
   COMMENT ON COLUMN COMTSMSDH.MEMBER IS '사용 안함';
   COMMENT ON COLUMN COMTSMSDH.SPHONE1 IS '문자 전송 메시지를 보내는 전화번호1';
   COMMENT ON COLUMN COMTSMSDH.SPHONE2 IS '문자 전송 메시지를 보내는 전화번호2';
   COMMENT ON COLUMN COMTSMSDH.SPHONE3 IS '문자 전송 메시지를 보내는 전화번호3';
   COMMENT ON COLUMN COMTSMSDH.SENDNAME IS '문자 전송 메시지를 보내는 사람 이름';
   COMMENT ON COLUMN COMTSMSDH.RPHONE1 IS '문자 전송 메시지를 받는 핸드폰 번호1';
   COMMENT ON COLUMN COMTSMSDH.RPHONE2 IS '문자 전송 메시지를 받는 핸드폰 번호2';
   COMMENT ON COLUMN COMTSMSDH.RPHONE3 IS '문자 전송 메시지를 받는 핸드폰 번호3';
   COMMENT ON COLUMN COMTSMSDH.RECVNAME IS '문자 전송 메시지를 받는 사람';
   COMMENT ON COLUMN COMTSMSDH.MSG IS '문자 전송 메시지';
   COMMENT ON COLUMN COMTSMSDH.URL IS '문자 전송 메시지 방식';
   COMMENT ON COLUMN COMTSMSDH.RDATE IS '문자 전송 메시지가 즉시전송이면 00000000, 예약전송일 경우 예약 발송 날짜';
   COMMENT ON COLUMN COMTSMSDH.RTIME IS '문자 전송 메시지가 예약전송일 경우 예약 발송 시간';
   COMMENT ON COLUMN COMTSMSDH.RESULT IS '문자 전송 메시지 전송 방식 (0-즉시 전송, R-예약전송, Y-에이전트까지 발송 성공, N-에이전트까지 발송 실패, 2-이통사까지 발송 성공, 4-이통사까지 발송 실패)';
   COMMENT ON COLUMN COMTSMSDH.KIND IS '문자 전송 메시지 방식';
   COMMENT ON COLUMN COMTSMSDH.ERRCODE IS '문자 전송 메시지 오류 코드';
   COMMENT ON COLUMN COMTSMSDH.C_RESULT IS '문자전송 상태 FLAG';
   COMMENT ON COLUMN COMTSMSDH.C_PID IS '문자전송한 사람 id';
   COMMENT ON COLUMN COMTSMSDH.C_SENDTIME IS '문자메시지 내부 전송시간';
   COMMENT ON COLUMN COMTSMSDH.C_MSGID IS '문자메시지의 내부 id값';
   COMMENT ON COLUMN COMTSMSDH.C_MSGPARAM IS '문자메시지 패러미터';
   COMMENT ON COLUMN COMTSMSDH.SEQNO IS 'SQL Server sequence';
   COMMENT ON COLUMN COMTSMSDH.C_USERID IS '발신자세션ID';
   COMMENT ON COLUMN COMTSMSDH.RECVTIME IS '수신자가 메세지를 확인한 시간';
   COMMENT ON COLUMN COMTSMSDH.MEDIATYPE IS 'LMS발송 업체';
   COMMENT ON TABLE COMTSMSDH  IS '즉시메시지관리';

  CREATE INDEX IX_COMTSMSDH_01 ON COMTSMSDH (C_RESULT);
  CREATE INDEX IX_COMTSMSDH_02 ON COMTSMSDH (C_SEQNO) ;
  CREATE INDEX IX_COMTSMSDH_03 ON COMTSMSDH (INDATE)  ;
  CREATE INDEX IX_COMTSMSDH_04 ON COMTSMSDH (RPHONE1, RPHONE2, RPHONE3) ;
  CREATE INDEX IX_COMTSMSDH_05 ON COMTSMSDH (C_RESULT, RESULT) ;
  CREATE INDEX IX_COMTSMSDH_06 ON COMTSMSDH (SPHONE1, SPHONE2, SPHONE3) ;
  CREATE INDEX IX_COMTSMSDH_07 ON COMTSMSDH (SENDNAME) ;

